name: Feature Request
description: Request a Feature
title: "Request - "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Tell us a little bit about what you'd like.
  - type: textarea
    id: Description
    attributes:
      label: Description
      description: Describe your dream feature.
    validations:
      required: true 
  